### ISSUE TITLE
Plugin not Work on Prefetch Stylesheet

### ISSUE THREAD

**Issue by Sysix** [rugk/website-dark-mode-switcher#17]
## Bug description
When I'm using my Stylesheet like this:

`<link ref="prefetch" href="style.css" onload="this.setAttribute('ref', 'stylesheet')" as="style">`

The Plugin will not activate on the new page reload. I need to deactivate (when it is already activate) and active it again to see the changes.

## Steps to reproduce

1. Add a Stylesheet File like on the Description
2. Activate the Plugin before loading the Page
3. Deactive and Activate the Plugin to see the changes

### Actual behavior
The Page is loading like a normal prefered White Page. The Dark-Scheme will be ignored.

### Expected behavior
After the "prefetch" loading of the Stylesheet, the Plugin should check the Stylesheet (like a normal one) and activate the changes 

## System

Operating system and version:  Win10 Pro (V. Number unknown)
Browser and version: Firefox  72
Add-on version: 

## Possible solution
Not check for  stylesheets  in document [See here](https://github.com/rugk/website-dark-mode-switcher/blob/master/src/content_scripts/applyColorSchemeCss.js#L100).

Else it should track the HTML Tags for `rel="stylesheet"` or `"rel="prefetch / preload" as="style"`

**Comment by rugk** [comment]
@Sysix Do you by chance have any test website or JSFiddle or so to reproduce this issue?

**Comment by rugk** [comment]
Hi, I have great news for you! So I guess, the latest [v2.0 release](https://github.com/rugk/website-dark-mode-switcher/releases/tag/v2.0) fixes this issue due to the way it now uses a completely new API to do "dark-mode-changing" "properly". For more information, please see the release notes. If the issue should not be fixed, please let me know.

As said, also let me know if you have a reproducer, then I can test that more properly and be sure it works. :upside_down_face:
