### ISSUE TITLE
Does not work on initial page load with NoScript

### ISSUE THREAD

**Issue by ybungalobill** [rugk/website-dark-mode-switcher#23]
## Bug description

Does not work on initial page load with NoScript enabled.

## Steps to reproduce

1. Install NoScript.
2. Go to a website with the dark theme media query that's not white-listed.

### Actual behavior

* The page loads with the default scheme.
* Clicking on the 'Dark Website Forcer' button *twice* switches to the dark theme.
* Disabling NoScript and reloading the page switches to the dark theme.

### Expected behavior

Should load in dark mode on the first try with NoScript enabled.

## System

Browser and version: Firefox 73.0
Add-on version: 1.1

## Possible solution

It should be possible to change the page CSS without running any Javascript in the context of the page. E.g. Stylish works with no issues on all pages.

**Comment by rugk** [comment]
Yeah, actually the add-on needs to run JS to get the CSS and re-inject it. However, AFAIK other add-ons should not really be able to stop the JS executed from other add-ons. So this definitively sounds like a bug. :thinking:

**Comment by rugk** [comment]
Hi, I have great news for you! According to my testing, the latest [v2.0 release](https://github.com/rugk/website-dark-mode-switcher/releases/tag/v2.0) fixes this issue due to the way it now uses a completely new API to do "dark-mode-changing" "properly". For more information, please see the release notes. If the issue should not be fixed, please let me know.

Note: Of course it cannot support websites where `prefers-color-scheme` was updated via JavaScript if JS is disabled. After all, that's the intend of NoScript, so I don't consider this a bug. :upside_down_face: 
But as for everywhere where (only) CSS is used to implement a dark mode on a website, the extension should (now) work.
