### ISSUE TITLE
Doesn't work with stylesheets imported with @import

### ISSUE THREAD

**Issue by Justin-CB** [rugk/website-dark-mode-switcher#28]
**Affected website:** 
justinbesterportfolio.xp3.biz

## Bug description
Extension fails to recognize the dark mode css.

## Steps to reproduce
1. Install dark mode forcer
2. Enable dark mode forcer
3. Goto justinbesterportfolio.xp3.biz
### Actual behavior
The website displays in light mode despite having dark mode CSS.
### Expected behavior
The website will style using the dark mode CSS.
## System
Operating system and version: 
Browser and version: Firefox 
Add-on version:

**Comment by rugk** [comment]
Oh I'm sorry, I debugged this your assessment was indeed correct, the cause for this issue is the `@import`ed style. It was in my mind that the browser would parse that correctly, but it does not.

**Comment by rugk** [comment]
So thanks for the report, this should be fixed in https://github.com/rugk/website-dark-mode-switcher/commit/fa7086ef875eaf350b605cc55f1db914c4a31b00, where I now recursively parse the stylesheets for such things.

Note [you could try out the development version](https://github.com/TinyWebEx/common/blob/master/CONTRIBUTING.md#coding) and report back whether it/everything works/you like it or what may still be adjusted, so I can do this before the next release. In case there is something to be done… :smile:
