### ISSUE TITLE
Cannot download from Firefox Addon Store

### ISSUE THREAD

**Issue by mbledkowski** [rugk/website-dark-mode-switcher#53]
## Bug description
Hi, I don't know why, but when I try do download this addon from Firefox's Add-on Store it shows "You need an updated version of Firefox for this extension" information. Other addons I can download just fine.

## Steps to reproduce
1. Go to https://addons.mozilla.org/en-US/firefox/addon/dark-mode-website-switcher/
![image](https://user-images.githubusercontent.com/23295125/155356819-9010d2d4-fc3b-4448-8242-28650f460b6d.png)

### Actual behavior
"You need an updated version of Firefox for this extension" information

### Expected behavior
Option to download this addon.

## System
Arch Linux x86_64, Linux 5.16.10-zen1-1-zen, Firefox version 97.0.1 (64 bit), all packages up to date

**Comment by rugk** [comment]
As indicated in other issues (https://github.com/rugk/website-dark-mode-switcher/issues/52) this is very likely an issue with `privacy.resistFingerprinting` or any other add-on or some Firefox tweaking tool or similar that could have set that option.

To check that, please open a new tab and go to `about:config`. If there is a warning, accept that. Then enter `privacy.resistFingerprinting` there. If it is enabled, then please disable it by double-clicking on it.

The problem is that for privacy reasons, Firefox overrides the user agent when that option is set.
Note that you also need to have that option disabled, because Firefox would also override that dark mode when that option is set. See https://github.com/rugk/website-dark-mode-switcher/issues/22 for more information.
